export default function Head() {
  return (
    <>
      <title>SpaceX Launch Timeline UI</title>
      {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
          <script src="https://harishchaudhari.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.0" async defer></script>
    </>
  )
}